---
title: "Introduction to Statistical Learning"
author: "Greg Foletta"
output:
  html_document:
    theme: cerulean
    highlight: tango
---

## Summary

These documents contain notes and completed exercises from the book [An Introduction to Statistical Learning in R](http://www.statlearning.com/).

All pages were completed in [RMarkdown](https://rmarkdown.rstudio.com/) with code written in [R](https://www.r-project.org/about.html) and equations
written in [LaTeX](https://www.latex-project.org). Pages were knitted into HTML using [knitr](https://yihui.name/knitr/).

[git](https://git-scm.com/) was used for source control and [GitHub Pages](https://pages.github.com/) is used for hosting.

## Caveats

These pages were put together to maximise my learnings from the book. As it is a learning exercise, there may be errors. If you see an error please raise an
[issue](https://github.com/gregfoletta/Introduction-to-Statistical-Learning/issues/new), referencing the chapter and the specific error. You are also most
welcome to branch, fix the error, and issue a pull request.

I have approached the labs and applied exercises from a different perspective than the book. The book uses base R concepts, where I have used concepts taken from
the [tidyverse](https://www.tidyverse.org/).

 The chapters were completed during my downtime over the period of a year. During this time I learnt not just about statistical techniques, but also different approaches
 to wrangling data and different concepts within the R language and the tidyverse. As such the approach to a similar task may differ between the earlier and later chapters.


## Chapter 2 - Statistical Learning

This chapter discusses statistical learning and assessing model accuracy.

* [Notes](Chapter_2/notes.html)

### Exercises 

* [Conceptual](Chapter_2/conceptual.html)
* [Applied](Chapter_2/applied.html)

## Chapter 3 - Linear Regression

This chapter discusses simple and multiple linear regressions, qualitative predictors, and comparisions to K-nearest neighbours.

* [Notes](Chapter_3/notes.html)

### Exercises
* [Lab](Chapter_3/lab.html)
* [Conceptual](Chapter_3/conceptual.html)
* [Applied](Chapter_3/applied.html)

## Chapter 4 - Classification

This chapter discusses logistic regression, linear and quadratic discriminant analysis, and K-nearest neighbours.

* [Notes](Chapter_4/notes.html)

### Exercises
* [Lab](Chapter_4/lab.html)
* [Conceptual](Chapter_4/conceptual.html)
* [Applied](Chapter_4/applied.html)

## Chapter 5 - Resampling Methods

This chapter discusses cross-validation, k-fold cross validation and bootstrapping.

* [Notes](Chapter_5/notes.html)

### Exercises
* [Lab](Chapter_5/lab.html)
* [Conceptual](Chapter_5/conceptual.html)
* [Applied](Chapter_5/applied.html)

## Chapter 6 - Linear Model Selection and Regularization

This chapter discusses subset selection (best subset, stepwise selection), shrinkage methods (ridge regression and lasso), and dimension reduction methods (principal components regression and partial least squares).

* [Notes](Chapter_6/notes.html)

### Exercises

* [Lab](Chapter_6/lab.html)
* [Conceptual](Chapter_6/conceptual.html)
* [Applied](Chapter_6/applied.html)

## Chapter 7 - Moving Beyond Linearity

This chapter discusses polynomials, splines, and general additative models (GAMs).

* [Notes](Chapter_7/notes.html)

### Exercises

* [Lab](Chapter_7/lab.html)
* [Conceptual](Chapter_7/conceptual.html)
* [Applied](Chapter_7/applied.html)

## Chapter 8 - Tree-based Methods

This chapter discusses regression and classification trees, as well as bagging, random forrests, and boosting.

* [Notes](Chapter_8/notes.html)

### Exercises

* [Lab](Chapter_8/lab.html)
* [Conceptual](Chapter_8/conceptual.html)
* [Applied](Chapter_8/appplied.html)

## Chapter 9 - Support Vector Machines

This chapter discusses classification using hyperplanes, leading to support vector machines.

* [Notes](Chapter_9/notes.html)

### Exercises

* [Lab](Chapter_9/lab.html)
* [Conceptual](Chapter_9/conceptual.html)
* [Applied](Chapter_9/applied.html)

## Chapter 10 - Unsupervised Learning

This chapter discusses unsupervised learning techniques including PCA and hierarchical clustering.

* [Notes](Chapter_10/notes.html)

### Exercises

* [Lab](Chapter_10/lab.html)
* [Conceptual](Chapter_10/conceptual.html)
* [Applied](Chapter_10/applied.html)
