# Introduction to Statistical Learning

## Chapter 2 - Statistical Learning

This chapter discusses statistical learning and assessing model accuracy.

* [Notes](Chapter_2/notes.md)

### Exercises 

* [Conceptual](Chapter_2/conceptual.md)
* [Applied](Chapter_2/applied.md)

## Chapter 3 - Linear Regression

This chapter discusses simple and multiple linear regressions, qualitative predictors, and comparisions to K-nearest neighbours.

* [Notes](Chapter_3/notes.md)

### Exercises
* [Lab](Chapter_3/lab.md)
* [Conceptual](Chapter_3/conceptual.md)
* [Applied](Chapter_3/applied.md)

## Chapter 4 - Classification

This chapter discusses logistic regression, linear and quadratic discriminant analysis, and K-nearest neighbours.

* [Notes](Chapter_4/notes.md)

### Exercises
* [Lab](Chapter_4/lab.md)
* [Conceptual](Chapter_4/conceptual.md)
* [Applied](Chapter_4/applied.md)

## Chapter 5 - Resampling Methods

This chapter discusses cross-validation, k-fold cross validation and bootstrapping.

* [Notes](Chapter_5/notes.md)

### Exercises
* [Lab](Chapter_5/lab.md)
* [Conceptual](Chapter_5/conceptual.md)
* [Applied](Chapter_5/applied.md)

## Chapter 6 - Linear Model Selection and Regularization

This chapter discusses subset selection (best subset, stepwise selection), shrinkage methods (ridge regression and lasso), and dimension reduction methods (principal components regression and partial least squares).

* [Notes](Chapter_6/notes.md)

### Exercises

* [Lab](Chapter_6/lab.md)
* [Conceptual](Chapter_6/conceptual.md)
* [Applied](Chapter_6/applied.md)

## Chapter 7 - Moving Beyond Linearity

This chapter discusses polynomials, splines, and general additative models (GAMs).

* [Notes](Chapter_7/notes.md)

### Exercises

* [Lab](Chapter_7/lab.md)
* [Conceptual](Chapter_7/conceptual.md)

## Chapter 8 - Tree-based Methods

This chapter discusses regression and classification trees, as well as bagging, random forrests, and boosting.

* [Notes](Chapter_8/notes.md)

### Exercises

* [Lab](Chapter_8/lab.md)
* [Conceptual](Chapter_8/conceptual.md)
* [Applied](Chapter_8/applied.md)

## Chapter 9 - Support Vector Machines

This chapter discusses classification using hyperplanes, leading to support vector machines.

* [Notes](Chapter_9/notes.md)

### Exercises

* [Lab](Chapter_9/lab.md)
* [Conceptual](Chapter_9/conceptual.md)
* [Applied](Chapter_9/applied.md)

## Chapter 10 - Unsupervised Learning

This chapter discusses unsupervised learning techniques including PCA and hierarchical clustering.

* [Notes](Chapter_10/notes.md)

### Exercises

* [Lab](Chapter_10/lab.md)
* [Conceptual](Chapter_10/conceptual.md)
* [Applied](Chapter_10/applied.md)
