<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Chapter 5 - Applied</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: #990073
   }

   pre .number {
     color: #099;
   }

   pre .comment {
     color: #998;
     font-style: italic
   }

   pre .keyword {
     color: #900;
     font-weight: bold
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: #d14;
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>



<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<h1>Chapter 5 - Applied</h1>

<pre><code class="r">library(ISLR)
library(broom)
library(modelr)
library(tidyverse)
</code></pre>

<h2>5)</h2>

<p><em>In Chapter 4, we used logistic regression to predict the probability of default using income and balance on the Default data set. We will now estimate the test error of this logistic regression model using the validation set approach. Do not forget to set a random seed before beginning your analysis.</em></p>

<h3>a)</h3>

<p><em>Fit a logistic regression model that uses income and balance to predict default.</em></p>

<pre><code class="r">default &lt;- as.tibble(Default)
default.log &lt;- glm(default~balance, data = default, family = binomial)
</code></pre>

<h3>b)</h3>

<p><em>Using the validation set approach, estimate the test error of this model. In order to do this, you must perform the following steps:</em></p>

<h4>i)</h4>

<p><em>Split the sample set into a training set and a validation set.</em></p>

<pre><code class="r">set.seed(1)
default_split &lt;- resample_partition(default, c(train = 0.5, test = 0.5))
</code></pre>

<h4>ii)</h4>

<p><em>Fit a multiple logistic regression model using only the training observations.</em></p>

<pre><code class="r">default_split_train &lt;- glm(default ~ balance, data = as.tibble(default_split$train), family = binomial)
</code></pre>

<h4>iii)</h4>

<p><em>Obtain a prediction of default status for each individual in the validation set by computing the posterior probability of default for that individual, and classifying the individual to the default category if the posterior probability is greater than 0.5.</em></p>

<pre><code class="r">as.tibble(default_split$test) %&gt;% 
    mutate(pred_default = ifelse(predict(default_split_train, ., type = &#39;response&#39;) &lt; 0.5, &quot;No&quot;, &quot;Yes&quot;))
</code></pre>

<pre><code>## # A tibble: 5,001 x 5
##    default student balance income pred_default
##    &lt;fct&gt;   &lt;fct&gt;     &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;       
##  1 No      No        1074. 31767. No          
##  2 No      No         529. 35704. No          
##  3 No      Yes        920.  7492. No          
##  4 No      No         826. 24905. No          
##  5 No      Yes        809. 17600. No          
##  6 No      No        1161. 37469. No          
##  7 No      No         237. 28252. No          
##  8 No      No        1113. 23810. No          
##  9 No      No           0  50265. No          
## 10 No      Yes        528. 17637. No          
## # ... with 4,991 more rows
</code></pre>

<h4>iv)</h4>

<p><em>Compute the validation set error, which is the fraction of the observations in the validation set that are misclassified.</em></p>

<pre><code class="r">as.tibble(default_split$test) %&gt;% 
    mutate(pred_default = ifelse(predict(default_split_train, ., type = &#39;response&#39;) &lt; 0.5, &quot;No&quot;, &quot;Yes&quot;)) %&gt;% 
    group_by(default, pred_default) %&gt;% 
    tally()
</code></pre>

<pre><code>## # A tibble: 4 x 3
## # Groups:   default [?]
##   default pred_default     n
##   &lt;fct&gt;   &lt;chr&gt;        &lt;int&gt;
## 1 No      No            4821
## 2 No      Yes             11
## 3 Yes     No             122
## 4 Yes     Yes             47
</code></pre>

<p>Out of 5001 observations, 11 + 122 are incorrect. The error rate is therefore (11 + 122) / 5001 = 2.65%</p>

<h3>c)</h3>

<p><em>Repeat the process in (b) three times, using three different splits of the observations into a training set and a validation set. Comment on the results obtained.</em></p>

<p>We&#39;ll be a bit lazy with this and use a for loop.</p>

<pre><code class="r">set.seed(2)
for (i in 1:3) {
    default_split &lt;- resample_partition(default, c(train = 0.5, test = 0.5))
    default_split_train &lt;- glm(default ~ balance, data = as.tibble(default_split$train), family = binomial)
    as.tibble(default_split$test) %&gt;% 
        mutate(pred_default = ifelse(predict(default_split_train, ., type = &#39;response&#39;) &lt; 0.5, &quot;No&quot;, &quot;Yes&quot;)) %&gt;% 
        group_by(default, pred_default) %&gt;% 
        tally() %&gt;% 
        print()
}
</code></pre>

<pre><code>## # A tibble: 4 x 3
## # Groups:   default [?]
##   default pred_default     n
##   &lt;fct&gt;   &lt;chr&gt;        &lt;int&gt;
## 1 No      No            4827
## 2 No      Yes             24
## 3 Yes     No              99
## 4 Yes     Yes             51
## # A tibble: 4 x 3
## # Groups:   default [?]
##   default pred_default     n
##   &lt;fct&gt;   &lt;chr&gt;        &lt;int&gt;
## 1 No      No            4826
## 2 No      Yes             23
## 3 Yes     No             113
## 4 Yes     Yes             39
## # A tibble: 4 x 3
## # Groups:   default [?]
##   default pred_default     n
##   &lt;fct&gt;   &lt;chr&gt;        &lt;int&gt;
## 1 No      No            4807
## 2 No      Yes             20
## 3 Yes     No             125
## 4 Yes     Yes             49
</code></pre>

<p>We get error rates of 2.4%, 2.8% and 2.7%.</p>

<h3>d)</h3>

<p><em>Now consider a logistic regression model that predicts the prob ability of default using income , balance , and a dummy variable for student . Estimate the test error for this model using the validation set approach. Comment on whether or not including a dummy variable for student leads to a reduction in the test error rate.</em></p>

<p>We modify the formula in the <code>glm()</code> to be <code>default ~ balance + student</code>. We then run the three validation set tests and get error percentages of 2.4%, 2.7% and 2.7%. There seems to be no reduction in the error rate by adding in the student variable.</p>

<h2>6)</h2>

<p><em>We continue to consider the use of a logistic regression model to predict the probability of default using income and balance on the Default data set. In particular, we will now compute estimates for the standard errors of the income and balance logistic regression co efficients in two different ways: (1) using the bootstrap, and (2) using the standard formula for computing the standard errors in the glm() function.</em></p>

<h3>a)</h3>

<p><em>Using the summary() and glm() functions, determine the estimated standard errors for the coefficients associated with income and balance in a multiple logistic regression model that uses both predictors.</em></p>

<pre><code class="r">glm(default ~ income + balance, data = default, family = &#39;binomial&#39;) %&gt;% tidy()
</code></pre>

<pre><code>## # A tibble: 3 x 5
##   term           estimate  std.error statistic   p.value
##   &lt;chr&gt;             &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept) -11.5       0.435         -26.5  2.96e-155
## 2 income        0.0000208 0.00000499      4.17 2.99e-  5
## 3 balance       0.00565   0.000227       24.8  3.64e-136
</code></pre>

<p>We see the standard error for the coefficients is 0.00000499 for income and 0.000227 for balance.</p>

<h3>b) &amp; c)</h3>

<p><em>Use the bootstrap to estimate the standard errors of the logistic regression coefficients</em></p>

<pre><code class="r">set.seed(1)
default %&gt;% 
    modelr::bootstrap(n = 20) %&gt;% 
    mutate(model = map(strap, ~glm(default~income+balance, data = .x, family = &#39;binomial&#39;))) %&gt;% 
    mutate(tidy = map(model, ~tidy(.x))) %&gt;% 
    unnest(tidy) %&gt;% 
    group_by(term) %&gt;% 
    summarise(avg_stderr = mean(std.error))
</code></pre>

<pre><code>## # A tibble: 3 x 2
##   term        avg_stderr
##   &lt;chr&gt;            &lt;dbl&gt;
## 1 (Intercept) 0.429     
## 2 balance     0.000225  
## 3 income      0.00000498
</code></pre>

<p>We see the average standard error to be 0.000225 for balance and 0.00000498 for income.</p>

<h3>d)</h3>

<p><em>Comment on the estimated standard errors.</em></p>

<p>The difference in the standard errors from the bootstrap compared to the formula is small: a 1% different from balance and a .2% difference for income.</p>

<h2>7)</h2>

<p><em>Compute the LOOCV error for a simple logistic regression model on the Weekly data set.</em></p>

<h3>a)</h3>

<p><em>Fit a logistic regression model that predicts Direction using Lag1 and Lag2</em></p>

<pre><code class="r">weekly &lt;- as.tibble(Weekly)
weekly.logistic &lt;- glm(Direction ~ Lag1 + Lag2, data = weekly, family = &#39;binomial&#39;)
</code></pre>

<h3>b)</h3>

<p><em>Fit a logistic regression model that predicts Direction using Lag1 and Lag2 using all but the first observation.</em></p>

<pre><code class="r">weekly.logistic.loo &lt;- glm(Direction ~ Lag1 + Lag2, data = weekly[-1,], family = &#39;binomial&#39;)
</code></pre>

<h3>c)</h3>

<p><em>Use the model from (b) to predict the direction of the first observation.</em></p>

<pre><code class="r">weekly[1,] %&gt;% 
    mutate(Prediction = ifelse(predict(weekly.logistic.loo, ., type = &#39;response&#39;) &gt; 0.5, &quot;Up&quot;, &quot;Down&quot;)) %&gt;% 
    select(Direction, Prediction)
</code></pre>

<pre><code>## # A tibble: 1 x 2
##   Direction Prediction
##   &lt;fct&gt;     &lt;chr&gt;     
## 1 Down      Up
</code></pre>

<p>The prediction was &#39;Up&#39;, but the true direction was &#39;Down&#39;.</p>

<h3>d)</h3>

<p><em>Write a for loop from i = 1 to i = n, where n is the number of observations in the data set, that performs each of the following steps:
    * Fit a logistic regression model using all but the ith observation to predict Direction using Lag1 and Lag2 .
    * Compute the posterior probability of the market moving up for the ith observation.
    * Use the posterior probability for the ith observation in order to predict whether or not the market moves up.
    * Determine whether or not an error was made in predicting the direction for the ith observation. If an error was made, then indicate this as a 1, and otherwise indicate it as a .</em></p>

<pre><code class="r">weekly %&gt;% 
    crossv_kfold(k = nrow(.)) %&gt;% 
    mutate(model = map(train, ~glm(Direction ~ Lag1 + Lag2, data = .x, family = &#39;binomial&#39;))) %&gt;% 
    mutate(prediction = map2_chr(model, test, ~ifelse(predict(.x, .y, type = &#39;response&#39;) &gt; 0.5, &quot;Up&quot;, &quot;Down&quot;))) %&gt;% 
    mutate(test_direction = map_chr(test, ~as.character(as.tibble(.x)[[&#39;Direction&#39;]]))) %&gt;% 
    summarise(error = mean(prediction != test_direction))
</code></pre>

<pre><code>## # A tibble: 1 x 1
##   error
##   &lt;dbl&gt;
## 1 0.450
</code></pre>

</body>

</html>
